# 使用データセット
- データセット名：Automobile Dataset
- 作成者/提供元：Dr.Daqing Chen, UCI Machine Learning Repository
- 入手元：https://archive.ics.uci.edu/dataset/10/automobile
- ライセンス：CC BY 4.0(クリエイティブ・コモンズ表示4.0国際)

# 機械学習モデル「線形回帰」
線形回帰とは、予測するための変数である説明変数と、予測したい変数である目的変数の関係を直線で表現する手法。<br>
説明変数を入手したときに得られる目的変数の予測値が、実際の目的変数の値に近づくようにモデルを学習させる。説明変数が1つの場合は単回帰分析、説明変数が複数の場合は重回帰分析と呼ばれる。<br>
単回帰分析はyを目的変数、xを説明変数をした時、2つのデータ間の関係性を
```
\begin{eqnarray}
y = ax + b
\end{eqnarray}
```
という一次関数の形で表す。<br>
このとき、係数aと切片bが分かれば、xを代入することで、yを予測することができる。

重回帰分析は、yは目的変数、x1,x2,・・・xnを説明変数としたとき、複数のデータ間の関係性を次のような一次関数の形で表す。
```
\begin{eqnarray}
y = a_1 \cdot x_1 + a_2 \cdot x_2 + \cdots + a_n \cdot x_n + b
\end{eqnarray}
```
ここで、a1,a2,・・・anは各説明変数に対応する係数(「回帰係数」)であり、bは切片。これらの係数と切片が分かれば、各説明変数x1,x2,・・・xnまでのn個の値を代入することで、yを予測することができる。

# データの理解
- 特徴量：車体の幅やエンジンの大きさなどを表すデータ
- 特徴量は量的データと質的データに分けられる
- 量的データは連続値で表現できるデータ
- 質的データはカテゴリーなどを表すデータ
- しかし必ず２つに分類されるとは限らない
- 線形回帰では、量的データだけでなく質的データも「ダミー変数化」することで扱えるようになる
- ダミー変数化とは表データにおける質的データを数値に変換する処理

# データの前処理
- データの前処理や機械学習モデルの構築には、pandasやscikit-learnといった便利な外部ライブラリが用意されている。これらのライブラリを活用することで、複雑な処理も簡単に実装でき、一からプログラムから書く手間を省くことができる。
- 外部ライブラリとは、Pythonの標準ライブラリ以外に、Python以外の組織や開発者が作成した機能をまとめたプログラムである.pyファイル(モジュール)をまとめたものを指す。これらを使用するには、通常、インストールとインポートという操作が必要。ただし、Google Colaboratoryでは、pandasやscikit-learnなどの主要なライブラリがあらかじめインストールされている。そのため、コードセルでimportの後に空白を開けてライブラリ名を記載するだけでこれらのライブラリをインポートでき、すぐに利用できる。
```
import ライブラリ名 # ライブラリのインポート
```

In [3]:
import pandas as pd # pdは慣習で付けている

- pandasの表の作成
- 変数名 = pd.DataFrame(2次元リスト)
- 表データを作るには、pandasのDataFrameのクラスを使う
- 表の各行の要素をリストとしてまとめてこのDataFrameに渡す
- 文字列はクォート'や"で囲む必要がある

In [4]:
df = pd.DataFrame([[57,120],[52,130],[55,115],[51,140]])
df

    0    1
0  57  120
1  52  130
2  55  115
3  51  140

DataFrameでは、データを行と列で管理している。縦方向に並んだ表の左側の番号をインデックス(index)、横方向に並んだ列の名前をカラム(columns)と呼ぶ。そしてデフォルトではインデックスとカラムには0から始まる連番が自動的に割り振られている。これはたった今作成したデータフレームでも確認できる。<br>
しかし、このままでは57や120という数字が何を表しているのかがわからない。そこで既存のデータフレームに後からカラム名を付ける方法がある。付けたいカラム名のリストを代入するだけ。またはデータフレームワークを作成する際にも、columns引数にカラム名のリストを指定することでカラム名を設定できる。

In [ ]:
df.columns = ['width','engine-size'] # データフレームのカラム名の変更
df

   width  engine-size
0     57          120
1     52          130
2     55          115
3     51          140

一度設定したカラム名を変更するには`rename`メソッドを利用できる。このメソッドではcolumns引数に変更前と変更後の列名の対応がわかるように指定する。

In [6]:
df = df.rename(columns={'width': '幅', 'engine-size' : 'エンジンの大きさ'})
df

    幅  エンジンの大きさ
0  57       120
1  52       130
2  55       115
3  51       140

- データフレームの`to_csv`メソッドを使用すると、作成した表をcsvファイルとして保存できる。
- シングルクオテーションで囲んだものが保存時のファイル名。index引数にFalseを渡していますが、これによりインデックス番号が保存されなくなる。
- CSV：comma separated values
- データの値と値の間をカンマで挟んで各列を分け、各行を改行を挟んで管理する形式を意味する。

In [7]:
df.to_csv('自動車のテストデータ', index = False)

`to_csv`メソッドで保存されたファイルはpandasの`read_csv`関数を使用し、データフレームとして変数に代入できる

In [8]:
df2 = pd.read_csv('自動車のテストデータ')
df2

    幅  エンジンの大きさ
0  57       120
1  52       130
2  55       115
3  51       140

## pandasを使ったデータの基本的な操作方法
- pandasのインポート方法
- データフレームの扱い方
- CSVファイルとしての保存方法

# モデルの構築
モデルの構築には、機械学習のライブラリである「scikit-learn」を使用する。このライブラリには、さまざまな機械学習モデルが用意されており、簡単に利用できるようになっている。<br>
インポート方法は、pandasとほぼ同じ。使用したいモデルが明確に決まっている場合、そのモデルだけを指定してインポートできる。なお、このライブラリの正式な名前は「scikit-laern」だが、import文では「sklearn」と記述する。

この場合、sklearnの線形モデル関連のlinear_modelモジュールから、線形回帰用のクラスであるLinearRegressionをインポートして使用する。
```
[scikit-learnのlinear_modelモジュールからLinearRegressionクラスをインポート]
from sklearn.linear_model import LinearRegression
```
fromの後にライブラリ名とモジュール名を指定し、その中からLinearRegressionクラスだけをインポートしている。なお、linear_modelモジュールには他にもさまざまなクラスが含まれているが、このように必要なクラスだけをインポートすることで、使用する際にも「モジュール名.クラス名」とせずにクラス名だけで使用することができる。

In [9]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

この2行だけで線形回帰のモデルを作成できる！<br>
LinearRegressionクラスをインポートした後に、二行目ではクラスをインスタンス化している。(クラスから実際に使える"モデルの実態"を作ることをインスタンス化と呼ぶ)<br>
このように、LinearRegressionというクラス名の後にかっこを付け、それを変数に代入することで、モデルのインスタンス化が簡単に行える。必要なクラスだけをインポートしているので、クラス名だけで使用できている。<br>
あとは実際にデータをこのモデルに学習させるだけで、予測モデルが完成する。

In [10]:
import pandas as pd 
test_data = pd.DataFrame([[65,120,12000],[70,115,15000],[66,130,13500],[64,133,12100],[67,127,14200]], columns = ['width', 'engine-size', 'price'])

次にこの表から説明変数と目的変数を分けて、機械学習モデルに学習させよう。特定の列だけを抜き出すには、列名をリストとして指定<br>
[['列名1','列名2']]のように抜き出したい列をカンマで区切ってリストにまとめ、それをさらに角かっこで囲むこてで、指定した列を抜き出すことができる。

In [11]:
x = test_data[['width', 'engine-size']]
x

   width  engine-size
0     65          120
1     70          115
2     66          130
3     64          133
4     67          127

目的変数tも同様に抜き出しますが、1列だけでよいので、リストではなく列名だけをそのまま指定する。今回は'price'

In [12]:
t = test_data['price']
t

0    12000
1    15000
2    13500
3    12100
4    14200
Name: price, dtype: int64

`scikit-learn`の機械学習モデルの学習には`fit`メソッドを利用する。

In [14]:
from sklearn import set_config
set_config(display='text')

model.fit(x, t)

LinearRegression()

今回は説明変数が'width'と'engine-size'の2つなので、
```
\begin{eqnarray}
y = a_1 \cdot x_1 + a_2 \cdot x_2  + b
\end{eqnarray}
```
という一次関数を想定している。

指定された切片は`intercept_`という属性に、係数は`coef_`という属性に格納させる。文字列では中かっこ(波かっこ)「{}」の中に変数名を書き、文字列全体の前にfを付けることで、変数の値を文字列の中に直接埋め込むことができる

In [15]:
print(f'推定された切片: {model.intercept_}')
print(f'推定された係数: {model.coef_}')

推定された切片: -45289.90362964966
推定された係数: [725.63271188  83.74313249]

ここで回帰係数$a$や切片$b$の推定には**最小二乗法**という手法が用いられる。<br>
これは、実際の目的変数の値(実測値)と予測値の差の二乗和を計算し、それが最小になるときの回帰係数と切片を求める方法。<br>
以下は説明変数が$m$個ある場合の、$i$番目のデータに対する予測値を表す式<br>
$$
f(x_i) = a_1 x_{i1} + a_2 x_{i2} + \dots + a_m x_{im} + b
$$
最小二乗法では、$y_i$を実測値として以下の式の値が最小になるように計算する
$$
\sum_{i=1}^{n} \left( y_i - f(x_i) \right)^2
$$

- 機械学習モデルのインポート -> from ... import ...
- モデルのインスタンス化 -> model = LinearRegression()
- データへのフィット -> model.fit()

# 欠損値、外れ値、可視化
## データの理解
データの理解は、その後のデータの加工やモデルの構築を行う上で、非常に重要なステップ。

In [16]:
import pandas as pd

df = pd.read_csv('自動車価格のData.csv')

df

     engine-size  city-mpg  curb-weight    price
0            130        21         2548  13495.0
1            130        21         2548  16500.0
2            152        19         2823  16500.0
3            109        24         2337  13950.0
4            136        18         2824  17450.0
..           ...       ...          ...      ...
200          141        23         2952  16845.0
201          141        19         3049  19045.0
202          173        18         3012  21485.0
203          145        26         3217  22470.0
204          141        19         3062  22625.0

[205 rows x 4 columns]

In [17]:
len(df)

205

データフレームの`head`メソッドを使うと、先頭から指定した件数分のデータを表示できる。指定件数はカッコ内に書く。末尾から特定の件数を確認したい場合は、`tail`メソッドを使う。例えば、以下のコードではいずれもカッコ内に10と書いてので、`head`メソッドで先頭10件と`tail`メソッドで末尾10件を表示できる。

In [18]:
df.head(10)

   engine-size  city-mpg  curb-weight    price
0          130        21         2548  13495.0
1          130        21         2548  16500.0
2          152        19         2823  16500.0
3          109        24         2337  13950.0
4          136        18         2824  17450.0
5          136        19         2507  15250.0
6          136        19         2844  17710.0
7          136        19         2954  18920.0
8          131        17         3086  23875.0
9          131        16         3053      NaN

In [19]:
df.tail(10)

     engine-size  city-mpg  curb-weight    price
195          141        23         3034  13415.0
196          141        24         2935  15985.0
197          141        24         3042  16515.0
198          130        17         3045  18420.0
199          130        17         3157  18950.0
200          141        23         2952  16845.0
201          141        19         3049  19045.0
202          173        18         3012  21485.0
203          145        26         3217  22470.0
204          141        19         3062  22625.0